### ISSUE TITLE
弄了个网站

### ISSUE THREAD

**Issue by cgoxopx** [cgoxopx/cgoxopx.github.io#1]
http://losoloso.xszz.gq    
php写的，用的免费空间。  
目前还有点问题。验证码总是显示不出来，估计是gd库的原因。    
@chainsx

**Comment by chainsx** [comment]
我看看啊。。。

**Comment by cgoxopx** [comment]
四年前的贴了

**Comment by chainsx** [comment]
github又给我推了一次
